inherit_from: .rubocop_todo.yml

# TODO: What's a better idiom?
Style/MultilineBlockChain:
  Enabled: false

# Nice, but a bit esoteric
Style/SymbolProc:
  Enabled: false
Style/WordArray:
  MinSize: 6

AllCops:
  Exclude:
    - 'bin/**'
    - 'db/schema.rb'