# Case-insensitive substring on the left,
# replacement on the right.
# Final line is a fall-through.

!omap
  broadcast: broadcast
  air: broadcast
  issue: broadcast
  published: broadcast
  release: broadcast
  created: created
  recorded: created
  performance: created
  revised: revised
  copyright: copyright
  '': uncataloged