# Case-insensitive substring on the left,
# replacement on the right.
#
# Order on the right dictates preference for main title.
#
# Final line is a fall-through.

!omap
  album: Album
  b roll: Raw Footage
  b-roll: Raw Footage
  element: Raw Footage
  field tape: Raw Footage
  raw: Raw Footage
  promo: Promo
  trailer: Promo
  advertis: Promo
  clip: Clip
  number: Episode Number
  episode: Episode
  epospde: Episode
  segment: Segment
  program: Program
  series: Series
  collection: Collection
  label: Label
  '': Uncataloged