# Case-insensitive substring on the left,
# replacement on the right.
# Final line is a fall-through.

!omap
  Agriculture: Agriculture
  Animal: Animals
  Antiques: Antiques and Collectibles
  Collectibles: Antiques and Collectibles
  Biography: Biography
  Business: Business
  Consumer Affairs: Consumer Affairs and Advocacy
  Cooking: Food and Cooking
  Food: Food and Cooking
  Crafts: Crafts
  Crime: Law Enforcement and Crime
  Law Enforcement: Law Enforcement and Crime
  Dance: Dance
  Economics: Economics
  Education: Education
  Employment: Employment
  Energy: Energy
  Environment: Environment
  Exercise: Exercise
  Film and Television: Film and Television
  Fine Arts: Fine Arts
  Gardening: Gardening
  Geography: Geography
  Global Affairs: Global Affairs
  World Affairs: Global Affairs
  Politics: Politics and Government
  Government: Politics and Government
  Health: Health
  History: History
  Holiday: Holiday
  Home Improvement: Home Improvement
  Humor: Humor
  Journalism: Journalism
  LGBT: LGBTQ
  Literature: Literature
  Poetry: Literature
  Local Communities: Local Communities
  Recorded Music: Recorded Music
  Music: Music
  Nature: Nature
  News: News
  Parenting: Parenting
  Performing Arts: Performing Arts
  Philosophy: Philosophy
  Public Affairs: Public Affairs
  Race and Ethnicity: Race and Ethnicity
  Religion: Religion
  Science: Science
  Social Issues: Social Issues
  Spanish Language: Spanish Language
  Sports: Sports
  Technology: Technology
  Theater: Theater
  Theatre: Theater
  Travel: Travel
  War : War and Conflict
  Weather: Weather
  Women: Women
  Military Forces and Armaments: Military Forces and Armaments
  Psychology: Psychology
  Architecture: Architecture
  Transportation: Transportation
  '': ''
