---
- slug: iowa
  name: Iowa!
  ids: [cpb-aacip_37-31cjt2qs, cpb-aacip_37-010p2nvv]
  thumbnail_url: http://mlamedia01.wgbh.org/aapb/thumbnail/cpb-aacip_37-010p2nvv.jpg
  md: |
    Four score and seven years ago our forefathers.
    Four score and seven years ago our forefathers.
    Four score and seven years ago our forefathers.
    Four score and seven years ago our forefathers.
    Four score and seven years ago our forefathers.

