---
- slug: iowa
  name: Iowa!
  ids: [cpb-aacip_37-31cjt2qs, cpb-aacip_37-010p2nvv]
  thumbnail_url: http://mlamedia01.wgbh.org/aapb/thumbnail/cpb-aacip_37-010p2nvv.jpg
  md: |
    I'm reluctant to hard-code too much of the design right now: 
    I'd suggest we just put images and links in the text until we're more confident
    about the arrangement, and then I could turn that into code.
    If you need a link to all results, this is an example: [Iowa!](/catalog?f[exhibits][]=Iowa!)

