# Quotes are optional, unless the string contains colons.
# If the image is sitting in the expected place on the media server,
# "thumbnail_url" can be omitted.

- id: cpb-aacip_221-0322853m
  org_name: PBS SoCal
  name: "Equal Rights Amendment: Is it Necessary?"
  
- id: cpb-aacip_28-3n20c4st80
  org_name: Pacifica Radio Archives
  name: "Homosexual in our Society (1958)"
  thumbnail_url: /thumbs/audio-digitized.jpg
  
- id: cpb-aacip_304-579s52r5
  org_name: WUSF
  name: "Superbugs: The Killer Viruses"
  
- id: cpb-aacip_322-04dnck6t
  org_name: WEDU
  name: "WEDU Interview: Bill Moyers"
  
- id: cpb-aacip_304-16c2g2nd
  org_name: WUSF
  name: "Deepwater Horizon: One Year Later"
  
- id: cpb-aacip_333-19f4qtr6
  org_name: PBS Guam
  name: "Handicapable: Why Not Me"
  
- id: cpb-aacip_328-77sn09w0
  org_name: Idaho Public Television
  name: "Idaho Reports: Right to Work"
  
- id: cpb-aacip_75-93gxddpx
  org_name: Thirteen WNET
  name: "New York Voices: Voices of Immigrants Post 9/11"
  
- id: cpb-aacip_28-bg2h70895r
  org_name: Pacifica Radio Archives
  name: "Fannie Lou Hamer Interview"
  thumbnail_url: /thumbs/audio-digitized.jpg
  
- id: cpb-aacip_37-83xsjcdw
  org_name: Iowa Public Television
  name: "The Mischkiets: Holocaust Survivors"
  
- id: cpb-aacip_17-117m16jx
  org_name: Louisiana Public Broadcasting
  name: "WWII Oral History with George C. Henry"
  
- id: cpb-aacip_245-97xkt033
  org_name: Maine Public Broadcasting Network
  name: "Interview with Margaret Chase Smith"
  
- id: cpb-aacip_500-9z90dj38
  org_name: WUOM for the National Association of Educational Broadcasters 
  name: "The American Town: A Self-Portrait; Lancaster County, Pennsylvania"
  thumbnail_url: /thumbs/audio-digitized.jpg
  
- id: cpb-aacip_500-dz03342k
  org_name: National Association of Educational Broadcasters
  name: "Panel Discussion on the Public Broadcasting Act of 1967"
  thumbnail_url: /thumbs/audio-digitized.jpg
  
- id: cpb-aacip_15-qn5z60c97r
  org_name: WGBH
  name: "Harvard Law Student Barack Obama Defends Professor at Rally"
  
- id: cpb-aacip_305-36tx99jd
  org_name: New England Public Radio
  name: "Lecture by Professor Howard Zinn on 'The New Student Radicalism'"
  thumbnail_url: /thumbs/audio-digitized.jpg
  
  - id: cpb-aacip_15-b853f4kv16 
  org_name: WGBH
  name: "Interview with Nguyen Cao Ky"
  
- id: cpb-aacip_81-48sbchx0
  org_name: WNED
  name: "Woman; Women's Health Care: A History"
  
- id: cpb-aacip_15-9fj29c7n
  org_name: WGBH
  name: "Interview with Presidential Candidate George Wallace"
  
- id: cpb-aacip_153-44bp0159
  org_name: Oregon Public Broadcasting
  name: "Henry Kissinger on Foreign Affairs"
  thumbnail_url: /thumbs/audio-digitized.jpg
  
- id: cpb-aacip_16-322bvw0h
  org_name: WILL Illinois Public Media
  name: "Access to Life: Perspectives on the Americans with Disabilities Act"
  
- id: cpb-aacip_507-gf0ms3kn9k
  org_name: NewsHour Productions
  name: "The Robert MacNeil Report: I.F. Stone"
  
- id: cpb-aacip_15-03qv9zz4
  org_name: WGBH
  name: "Debate on the Women's Liberation Movement Between Germaine Greer and William F. Buckley"
  thumbnail_url: /thumbs/audio-digitized.jpg
  
- id: cpb-aacip_153-472v749x
  org_name: Oregon Public Broadcasting
  name: "Speech by President George W. Bush in Portland, Oregon"
  
- id: cpb-aacip_37-20sqvcx0
  org_name: Iowa Public Television
  name: "President Nixon's Visit to Iowa in 1971"
  
- id: cpb-aacip_260-42n5tgf3
  org_name: Wyoming PBS
  name: "Main Street, Wyoming: Sacred Sites"
  
- id: cpb-aacip_60-70msbm1d
  org_name: Mississippi Public Broadcasting
  name: "Conversations: International Museum of Muslim Cultures"
  
 - id: cpb-aacip_41-881jxfq8
  org_name: South Carolina ETV
  name: "Interview with Governor Bill Clinton of Arkansas"
  
- id: cpb-aacip_37-97kps40n
  org_name: Iowa Public Television
  name: "Interview with Presidential Candidate Rev. Jesse Jackson"
  
- id: cpb-aacip_15-hd7np1wp4c
  org_name: WGBH
  name: "Michael Dukakis Declares Presidential Candidacy"
